X, Y = array(openCSV('ressources/fichier_point.csv'))
Xc, Yc, R, n = cercle(X, Y)
E_max, E_min, dc = circularite(Xc, Yc, R, X, Y)
Xmax, Ymax = traceCercle(Xc, Yc, R + E_max, 1000)
Xmin, Ymin = traceCercle(Xc, Yc, R - E_min, 1000)
plt.plot(X, Y, 'rx')
plt.plot(Xmax, Ymax, 'g')
plt.plot(Xmin, Ymin, 'g')
plt.text(0, 0, f'dc = {dc:.2f}')
plt.show()
