\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{sebaClass}[2021/01/29 Personal class for my courses]

\LoadClass[a4paper]{article}

% Basics
\RequirePackage{lmodern}         % Polices modernes
\RequirePackage[francais]{babel} % Eléments typo français
\RequirePackage[utf8]{inputenc}  % Encodage d'entrée
\RequirePackage[T1]{fontenc}     % Encodage de sortie
% \RequirePackage{tcolorbox}       % De belles box

% Couleurs
\RequirePackage{couleurs}

% Mise en page
\RequirePackage{layout}

% Compteurs personnels
\RequirePackage{compteur}

% Codes informatiques
\RequirePackage{code}

% Maths
\RequirePackage{maths}

% Images
\RequirePackage{images}

% Hyperliens
\RequirePackage{hyper}